AmbitionEng/django-pgtrigger

README.rst
docs/index.rst
docs/package.rst
docs/tutorial.rst
pgtrigger/__init__.py
pgtrigger/core.py
pgtrigger/tests/models.py
pgtrigger/tests/test_core.py
poetry.lock
pyproject.toml
settings.py

@tomage this adds:
1. The ability to "name" triggers so that they can be referenced/loaded in other interfaces
2. The ability to ignore triggers dynamically in a single thread of execution.
With ``pgtrigger.ignore``, one can now ignore trigger execution dynamically in a thread of code without doing an `ALTER` or other operation.
This feature is a double edge sword. On one hand, it allows someone to bypass trigger code, but it also opens up legitimate use cases that are only solved by triggers, and it also helps solve adoption of people converting their codebase to be more protected.
Wtih `pgtrigger.ignore`, one has the ability to create "official interfaces" for their project. For example, this code only lets users be created from one interface:
```
from django.db import models …
```

Allow dynamic ignoring of triggers

---

docs/commands.rst
docs/index.rst
docs/toc.rst
docs/tutorial.rst
pgtrigger/core.py
pgtrigger/management/commands/pgtrigger.py
pgtrigger/tests/models.py
pgtrigger/tests/test_commands.py
pgtrigger/tests/test_core.py

Adds the ability to manage triggers by name
with the ``manage.py pgtrigger`` management command. This
change includes the following subcommands:
- ``manage.py pgtrigger ls``: List all triggers, their installation
status, and whether they are enabled or disabled.
- ``manage.py pgtrigger install``: Install triggers.
- ``manage.py pgtrigger uninstall``: Uninstall triggers.
- ``manage.py pgtrigger enable``: Enable triggers.
- ``manage.py pgtrigger disable``: Disable triggers.
- ``manage.py pgtrigger prune``: Prune triggers.
Because of this change, names are now enforced for every trigger
and must be unique for every model. Users that wish to
upgrade to this version must now supply a ``name`` keyword
argument to their triggers.
Docs were updated with references to the new management commands. …

Trigger management commands

---

settings.py

Some processes, such as building the documentation, doesn't require a full setup, such as a running database. Hence those builds tend to run without the DATABASE_URL environment variable even set. But `settings.py` assumes it is, as it copies the DB and modifies it's name slightly, which breaks the documentation builds.
Replicated locally by making sure `DATABASE_URL` was unset  and then run `poetry run make docs` and got the following exception:
```python
...
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/home/tomage/src/django-pgtrigger/settings.py", line 23, in <module>
DATABASES['other']['NAME'] += '_other'
KeyError: 'NAME'
```
Here's a screen-shot from readthedocs.com build …

Optionally change "other" DB name if set at all

---

pgtrigger/core.py
pgtrigger/tests/test_core.py

Previously triggers were installed with a broad try/except in order to ignore
errors when installing duplicate triggers. This caused invalid triggers to
not be installed with no errors thrown.
The code was updated to catch the specific exception for duplicate triggers
and allow other trigger errors to surface. A failing test case was
added.
Type: bug

Throw errors on invalid trigger definitions.

---

docs/tutorial.rst

Looks like this name was incorrectly copied from the previous example.

Fix incorrect name in example

---

docs/tutorial.rst
pgtrigger/__init__.py
pgtrigger/core.py
pgtrigger/tests/test_core.py

Previously one had to subclass a trigger and override ``get_declare`` in
order to change how the "DECLARE" fragment of a trigger was rendered.
Users can now provide ``declare`` to the instantiation of a trigger.
The documentation was updated to reflect this change.
Type: feature

Add the "declare" portion of a trigger as a top-level attribute

---

README.rst
docs/tutorial.rst
pgtrigger/core.py
pgtrigger/tests/test_core.py

django-pgtrigger now ensures that generated postgres IDs are
lowercase. Postgres IDs are case insensitive, and it django-pgtrigger
had issues dealing with names that had a mix of cases.
Type: bug

Ensure that generated postgres IDs are lowercase

---

README.rst
docs/commands.rst
docs/index.rst
docs/tutorial.rst
pgtrigger/apps.py
pgtrigger/core.py
pgtrigger/tests/models.py
pgtrigger/tests/test_core.py
pgtrigger/tests/test_multi_db.py
pyproject.toml
settings.py

Triggers can now be specified with the ``triggers`` attribute of a model's Meta
options. This still works alongside the old method of using ``pgtrigger.register``.
Type: feature
@PaulGilmartin this should make trigger specification a bit cleaner. Although Django doesn't allow one to override model meta options, this seems to be the approach that everyone else takes

Triggers can be specified in model Meta options plus other fixes

---

pgtrigger/core.py
pgtrigger/tests/test_core.py

Triggers with conditions that change were not successfully
re-installed with ``pgtrigger.install``. Note that this only affects
legacy installation and not installation with the new migration system.
Type: bug
Addresses https://github.com/Opus10/django-pgtrigger/issues/52

Fixed issue re-installing triggers with different conditions.

---

README.rst
pgtrigger/core.py
pgtrigger/tests/test_core.py

``pgtrigger.ignore`` avoids injecting SQL when transactions are in a failed
state, allowing for one to use nested transactions while ignoring triggers.
Type: bug

Fixes ignoring triggers with nested transactions

---

docs/api_reference.rst
docs/basics.rst
pgtrigger/__init__.py
pgtrigger/core.py
pgtrigger/tests/test_core.py

Triggers now have an optional ``timing`` argument. If set, triggers
will be created as "CONSTRAINT" triggers that can be deferred.
When ``timing`` is set to ``pgtrigger.Immediate``, the trigger will
run at the end of a statement. ``pgtrigger.Deferred`` will cause
the trigger to run at the end of the transaction.
Note that deferrable triggers must have both
``pgtrigger.After`` and ``pgtrigger.Row`` values set for the
``when`` and ``level`` attributes.
Type: feature
Addresses #14

Added deferrable triggers

---

pgtrigger/core.py
pgtrigger/tests/test_multi_db.py
pyproject.toml

``pgtrigger.ignore`` now uses the connection of the database router
when ignoring triggers.
Type: bug

Fixed issues using ``pgtrigger.ignore`` with multiple databases

---

pgtrigger/apps.py
pgtrigger/migrations.py

``django-pgtrigger`` trigger migrations are interoperable with Postgis and
other Postgres-flavored database backends.
Type: bug

Ensure interoperability with other Postgres backends

---

docs/advanced_db.rst
pgtrigger/installation.py
pgtrigger/tests/models.py

Paritioned table support introduced a bug in using trigger management
commands for Postgres 12 and under. This has been fixed.
Type: bug
Addresses #96

Pruning/installations fixed for Postgres versions 12 and under.

---

docs/faq.rst
pgtrigger/compiler.py
pgtrigger/contrib.py
pgtrigger/core.py
pgtrigger/migrations.py
pgtrigger/tests/test_core.py

Triggers that override ``get_func`` or otherwise generate dynamic SQL are properly reflected
in migrations when the underlying implementation changes. Along with this, migrations now serialize
SQL objects instead of trigger classes, making it more robust when reversing migrations or
updating underlying implementations of existing triggers.
This change updates the hashes of all triggers and thus re-creates all triggers when running
``makemigrations`` or when manually installing them.
Type: bug
Addresses #91

Migrations properly serialize dynamic triggers and add better support for reverse migrations

---

Makefile
README.rst
docs/cookbook.rst
docs/index.rst
docs/module.rst
pgtrigger/__init__.py
pgtrigger/contrib.py
pgtrigger/tests/test_contrib.py

The ``pgtrigger.ReadOnly`` trigger protects updates on models and takes an optional ``fields`` or ``exclude`` argument to specify which fields are read only. If no arguments are provided, the entire model is read only.
Type: feature

Added ``ReadOnly`` trigger for uneditable models and fields

---

README.md
pgtrigger/migrations.py
pgtrigger/tests/test_migrations.py

Fields of trigger conditions can now have their types updated in non-atomic migrations.
Type: bug
@kekekekule I wanted to quickly address the issue at #136 and fix some things in your PR at https://github.com/Opus10/django-pgtrigger/pull/136. I thought it would be easiest to get this in another PR and deploy since I'm going to be away for a bit. I made sure you are the author of the commit, so you will get credit in the release. I also added you to the README as a contributor. Thanks for your contributions!
I believe that this individual operation still needs to be atomic, even if it's in a non-atomic migration. It's dangerous to drop a trigger outside of a transaction as it could lead to data loss for django-pghistory users and other use cases where triggers are necessary to be installed …

Fix issues updating triggers in non-atomic migrations

---

pgtrigger/migrations.py
tox.ini

Thanks to #148 I managed to find a fix to make pg-trigger compatible with Django 5.1
> Django 5.1 switched to [namedtuples for migration dependencies](https://github.com/django/django/commit/7dd3e694db17bc34f9ce73e516f853ebd16e19e7).
> 
> pgtrigger's [migration patching will also need to be updated 👍](https://github.com/Opus10/django-pgtrigger/blob/3c2669bfb97500fc53edeefa981fa74da5412067/pgtrigger/migrations.py#L148)
NB: It would be nice to add Django "main" version to the testing grid so that issue are discovered soon enough before the official releases

Add Django 5.1 compatibility to MigrationAutodetectorMixin

---

pgtrigger/migrations.py

fix: skip abstract models in migrations

---

pgtrigger/runtime.py

Account for `execute_result` being `None` as was done in pghistory: https://github.com/Opus10/django-pghistory/pull/156
Fixes https://github.com/Opus10/django-pgtrigger/issues/169

Account for execute result being `None`

---

pgtrigger/core.py

Removed breaking typing_extensions import

---

docs/basics.md

This seems to have been incorrect from the beginning (since 6916c14136b4d03ebb9c94376a1e97772a90c965).
(Combining operations requires them to be an instance of `Operation`, which `UpdateOf` inherits from.)

docs: Remove incorrect warning on combining pgtrigger.UpdateOf

---

pgtrigger/compiler.py
pgtrigger/core.py
pgtrigger/migrations.py

I'm considering using `django-pgtrigger` in a [project](https://salsa.debian.org/freexian-team/debusine) that's fully-typed, and in my draft branch I found that I had to add a few `type: ignore[no-untyped-call]` comments to a migration.  This should help.  Some of the annotations are of course my best-effort guesses from hunting around elsewhere in the code.

Add more type annotations to pgtrigger.{compiler,migrations}

---

CHANGELOG.md
pgtrigger/management/commands/pgtrigger.py
pyproject.toml

Fixes #213 
Now options such as `--skip-checks` can be used with `manage.py pgtrigger`. Thanks to @adamchainz blog article at https://adamj.eu/tech/2024/08/14/django-management-command-sub-commands/!

Fix use of core django management command options when using pgtrigger command
